awesome_itech_project/awesome_itech_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from registration.backends.simple.views import RegistrationView
from registration.forms import RegistrationFormUniqueEmail
from django.conf import settings

class MyRegistrationView(RegistrationView):
    form_class=RegistrationFormUniqueEmail
    def get_success_url(self, user):
        return '/teambuilder/edit-profile/'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'awesome_itech_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^teambuilder/', include('teambuilder.urls', namespace='teambuilder')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
)

# let's just use django for now to serve static media as our application does not anticipate any load at the moment
urlpatterns += patterns(
    'django.views.static',
    (r'^media/(?P<path>.*)',
    'serve',
    {'document_root': settings.MEDIA_ROOT}), )

awesome_itech_project/teambuilder/urls.py
from django.conf.urls import patterns, include, url
from teambuilder import views

app_name = 'teambuilder'
urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^create-team/$', views.create_team, name='create_team'),
    url(r'^add-course/$', views.add_course, name='add_course'),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
    url(r'^edit-profile/$', views.edit_profile, name='edit_profile'),
    url(r'^team/(?P<team_name_slug>[\w\-]+)/$', views.team_details, name='team_detail'),
    url(r'^team/(?P<team_name_slug>[\w\-]+)/edit/$', views.edit_team, name='edit_team'),
    url(r'^course/(?P<course_name_slug>[\w\-]+)/$', views.course_details, name='course_detail'),
    url(r'^course/(?P<course_name_slug>[\w\-]+)/edit/$', views.edit_course, name='edit_course'),
    url(r'^course/(?P<course_name_slug>[\w\-]+)/teams/$', views.view_course_teams, name='view_course_teams'),
    url(r'^find-team/$', views.find_team, name='find_team'),
    url(r'^search-team/$', views.search_team, name='search_team'),
    url(r'^team/(?P<team_name_slug>[\w\-]+)/send-request/$', views.join_team, name='join_team'),
    url(r'^team/(?P<team_name_slug>[\w\-]+)/cancel-request/$', views.cancel_request, name='cancel_request'),
    url(r'^team/(?P<team_name_slug>[\w\-]+)/view-requests/$', views.view_requests, name='view_requests'),
    url(r'^team/(?P<team_name_slug>[\w\-]+)/view-members/$', views.view_team_members, name='view_team_members'),
    url(r'^request/(?P<request_id>[\w\-]+)/accept/$', views.accept_request, name='accept_request'),
    url(r'^request/(?P<request_id>[\w\-]+)/reject/$', views.reject_request, name='reject_request'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^unauthorized/$', views.unauthorized, name='unauthorized'),
    url(r'^page-not-found/$', views.page_not_found, name='page_not_found'),
    url(r'^course/(?P<course_name_slug>[\w\-]+)/merge-teams/$', views.merge_teams, name='merge_teams'),

)

awesome_itech_project/teambuilder/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.core.validators import MinValueValidator


def upload_location(instance, filename):
    return 'profile_images/{0}/{1}'.format(instance.user.username, filename)


class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    phone_number = models.CharField(max_length=15, blank=True)
    about_me = models.TextField(max_length=500, blank=True)
    picture = models.ImageField(upload_to=upload_location, default='default-avatar.jpg')
    role = models.CharField(max_length=15, null=True)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username


class Course(models.Model):
    code=models.CharField(max_length=15,unique=True)
    name=models.CharField(max_length=100,unique=True)
    course_password=models.CharField(max_length=15, null=False)
    team_size = models.IntegerField(validators=[MinValueValidator(2)])
    add_date=models.DateTimeField(default=datetime.now(), null=False)
    creator=models.ForeignKey(User)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Course, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


class Team(models.Model):
    name=models.CharField(max_length=100, unique=True)
    course=models.ForeignKey(Course)
    creator = models.ForeignKey(User)
    current_size=models.IntegerField(default=1)
    creation_date=models.DateTimeField(default=datetime.now(), null=False)
    required_skills=models.TextField(max_length=500)
    description=models.TextField(max_length=500)
    slug = models.SlugField()
    merge_with = models.ForeignKey('self', null=True)
    status = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Team, self).save(*args, **kwargs)

    def __unicode__(self):
         return self.name

    def available_slots(self):
        return self.course.team_size - self.current_size


class Memberrequest(models.Model):
    user=models.ForeignKey(User)
    status=models.CharField(max_length=10, default="pending")
    request_date=models.DateTimeField(default=datetime.now(), null=False)
    team = models.ForeignKey(Team)

    def __unicode__(self):
        return  self.user.username + "," + self.team.name

awesome_itech_project/teambuilder/forms.py
from django import forms
from django.contrib.auth.models import User
from models import Team,Course,UserProfile
from models import Team, Course


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password',)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password', 'email', 'first_name', 'last_name')


class TeamForm(forms.ModelForm):
    course_password = forms.CharField(max_length=15, required=True)

    class Meta:
        model = Team
        fields = ('name', 'course', 'required_skills','description')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone_number', 'about_me', 'role')


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('code', 'name', 'course_password', 'team_size',)

awesome_itech_project/teambuilder/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from teambuilder.forms import UserForm,TeamForm,CourseForm
from teambuilder.models import Team, Course, Memberrequest,UserProfile,User
from teambuilder.forms import UserForm,TeamForm,ProfileForm
from django.contrib.auth.decorators import login_required
from datetime import datetime


# Create your views here.
def index(request):
    teams = Team.objects.filter(status=True).order_by('-creation_date')[:5]  # get the top 5 teams ordered by most recently created
    courses = Course.objects.order_by('-add_date')[:5]  # get the top 5 courses ordered by most recently created
    context_dict = {}
    context_dict['teams'] = teams
    context_dict['courses'] = courses
    return render(request, 'teambuilder/index.html', context_dict)  # render the template file containing courses and teams


def about(request):
    return render(request, 'teambuilder/about.html', {})


@login_required  # user has to be logged in to create a team
def create_team(request):
    context_dict = {}

    context_dict['courses'] = Course.objects.order_by('name')  # get all the available courses
    if request.method == 'POST':  # user is sending data to the server#
        team_form = TeamForm(data=request.POST)
        context_dict['team_form'] = team_form

        # check if the sent data is valid
        if team_form.is_valid():

            # if data is valid, process team creation
            course_password = request.POST['course_password']
            course_id = request.POST['course']
            course = Course.objects.get(pk=course_id)

            team = team_form.save(commit=False)  # capture user input but don't save yet

            if course_password == course.course_password:
                # if user entered the correct course password, save the created team

                team.creator = request.user
                created_before = Team.objects.filter(course=course, creator=team.creator, status = True) #check if user has created an active team for the course previously

                if len(created_before) > 0:  # user has already created a team for the course. Deny team creation request
                    context_dict['error'] = "You have already created a team for this course before"
                else:
                    # user creating first team for the course. accept the request and save the team
                    team.name = team.name.title()
                    team.save()
                    context_dict['created'] = True
                    return HttpResponseRedirect('/teambuilder/team/'+team.slug+'/')  # redirect user to the team page of newly created team

            else:
                # incorrect password entered for course. Notify user of that
                context_dict['error'] = "Invalid course password provided"
                context_dict['created'] = False

                # also pass the entered data to template file to redisplay it
                context_dict['team'] = team


        else:
            # data passed in by user failed validation. Notify user of that
            context_dict['errors'] = team_form.errors

    return render(request, 'teambuilder/create_team.html', context_dict)

@login_required # user has to be logged in to view a user's profile
def profile(request, username):
    context_dict = {}

    try:  # if user has a profile, get and pass the profile to the template file or else create an empty one
        u = User.objects.get(username=username)
        up = UserProfile.objects.get_or_create(user=u)[0]
        context_dict['profile'] = up

    except User.DoesNotExist:
        return HttpResponseRedirect('/teambuilder/page-not-found/')
    except UserProfile.DoesNotExist:
        pass

    return render(request, 'teambuilder/profile.html', context_dict)

@login_required # user has to be logged in to edit profile
def edit_profile(request):
    context_dict = {}
    user = request.user  # get logged in user
    try:
        profile2 = UserProfile.objects.get_or_create(user=user)[0]  # get user profile or create an empty one if none exists

        if request.method == 'POST':  # if user is posting data to server

            profile_form = ProfileForm(data=request.POST, instance=profile2)

            # use a UserProfile object to store data collected in case validation fails
            uprofile = UserProfile(about_me=request.POST['about_me'],
                                   phone_number=request.POST['phone_number'], user=request.user)

            # check the user profile part for validity
            if profile_form.is_valid():
                # if form is valid, save
                # save the user details part first
                user.first_name = request.POST['first_name']
                user.last_name = request.POST['last_name']
                user.save()

                user_profile = profile_form.save(commit=False)
                if 'picture' in request.FILES:  # if user added a photo, add the photo to user's profile
                    user_profile.picture = request.FILES['picture']
                user_profile.save()
                context_dict['created'] = True
                context_dict['profile'] = user_profile
            else:
                # else show errors
                context_dict['errors'] = profile_form.errors
                context_dict['profile'] = uprofile  # validation failed. pass already entered data back to the user

        else:  # user is just requesting data from server i.e. making a GET request
            context_dict['profile'] = profile2

    except UserProfile.DoesNotExist:
        pass

    return render(request, 'teambuilder/edit_profile.html', context_dict)


def team_details(request, team_name_slug):

    context_dict = {}
    try:
        team = Team.objects.get(slug=team_name_slug)  # get team with the specified team name slug
        context_dict['team'] = team

        # check if user has previously requested to join the team
        user = request.user  # get the logged in user

        if user.is_authenticated():
            context_dict['profile'] = UserProfile.objects.get(user=user)  # get the user's profile
            try:
                # if user has a pending request to join the team, pass that request to the template file
                mr = Memberrequest.objects.get(team=team, user=user, status="pending")
                context_dict['member_request'] = mr

            except Memberrequest.DoesNotExist:
                pass

            #check if user has an already accepted request for that team
            try:
                mr2 = Memberrequest.objects.get(team=team,user=user,status="accepted")

                if mr2: # if an accepted request exists, pass True to the template file.
                    context_dict['accepted_request'] = True

            except Memberrequest.DoesNotExist:
                pass

    except Team.DoesNotExist:
        return HttpResponseRedirect('/teambuilder/page-not-found/')

    return render(request, 'teambuilder/team_detail.html', context_dict)


def find_team(request):
        team_list = []
        starts_with = ''
        if request.method == 'GET':
                starts_with = request.GET['suggestion']
        team_list = get_team_list(20, starts_with)

        return render(request, 'teambuilder/find_team.html', {'team_list': team_list })


def get_team_list(max_results=0, starts_with=''):
        team_list = None
        team_list1 = None
        course_list = None
        if starts_with:
                team_list = Team.objects.filter(name__istartswith=starts_with)
                course_list = Course.objects.filter(name__istartswith=starts_with)
                for course in course_list:
                        if team_list:
                            team_list1=Team.objects.filter(course=course)
                            for team in team_list1:
                               team_list.append(team)
                        else:
                               team_list = Team.objects.filter(course=course)

        else:
            team_list=Team.objects.all()
        if max_results > 0:
                if team_list.count() > max_results:
                        team_list = team_list[:max_results]

        return team_list


def search_team(request):
        team_list=[]
        team_list=Team.objects.all()
        return render(request, 'teambuilder/search_team.html', {'team_list': team_list })


@login_required  # user has to be logged in to add a course
def add_course(request):
    context_dic = {}
    if request.method == 'POST': # user is sending data
        course_form = CourseForm(request.POST) # create form instance with submitted data

        # if form is valid, create a new Model instance of course and save it
        if course_form.is_valid():
            course = course_form.save(commit=False)
            course.creator = request.user
            course.save()
            context_dic['created'] = True

        # else form has errors. Add those errors to the context dictionary for rendering on the template file
        else:
            context_dic['errors'] = course_form.errors

    # user is requesting data. Create and send back an empty form
    else:
        course_form=CourseForm()
        context_dic['course_form']=course_form

    return render(request, 'teambuilder/add_course.html', context_dic)


@login_required # user has to be logged in to send a request to join a team
def join_team(request, team_name_slug):
    user = request.user
    try:
        team = Team.objects.get(slug=team_name_slug)
        Memberrequest.objects.get_or_create(user=user, team=team, status="pending")  # using get_or_create to prevent user
                                                # from sending a join request twice to the same team if an already pending

awesome_itech_project/templates/teambuilder/change_password.html
{% extends 'base.html' %}
{% block title_block %}Reset password {% endblock %}
{% block body_block %}
    <p>This is the reset password page</p>
{% endblock %}

awesome_itech_project/templates/teambuilder/course_detail.html
{% extends 'base.html' %}
{% block title_block %}{{course.name}} details {% endblock %}
{% block body_block %}
    <h2>{{course.name}} details</h2>
       <div class="row">
           <div class="col-lg-12">
               <ul class="breadcrumb">
                    <li><a href="{% url 'teambuilder:index' %}">Home</a></li>
                    <li class="active">{{course.name}} </li>
               </ul>
           </div>
       </div>

    <div class="well">
        <div class="table-responsive">
            <table class="table">
                <tbody>
                    <tr>
                        <td>Code</td>
                        <td>{{course.code}}</td>
                    </tr>
                    <tr>
                        <td>Name</td>
                        <td>{{ course.name}}</td>
                    </tr>
                    <tr>
                        <td>Creator</td>
                        <td><a href="{% url 'teambuilder:profile' course.creator.username %}">{{course.creator.username}}</a></td>
                    </tr>
                    <tr>
                        <td>Required team size</td>
                        <td>{{course.team_size}}</td>
                    </tr>

                    {% if creator %}
                        <tr>
                            <td>Course password</td>
                            <td>{{course.course_password}}</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>

        <a class="btn btn-primary" href="/teambuilder/course/{{course.slug}}/teams/">View teams
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> </a>

        {% if creator  %}
            <a class="btn btn-primary" href="/teambuilder/course/{{course.slug}}/edit/">Edit course
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>
        {% endif %}
    </div>
{% endblock %}

awesome_itech_project/templates/teambuilder/create_team.html
{% extends 'base.html' %}
{% block title_block %}Build a team {% endblock %}
{% block body_block %}
    <h2>Create team</h2>
       <div class="row">
           <div class="col-lg-12">
               <ul class="breadcrumb">
                    <li><a href="{% url 'teambuilder:index' %}">Home</a></li>
                   <li><a href="{% url 'teambuilder:dashboard'  %}">Dashboard</a></li>
                    <li class="active">Create team</li>
               </ul>
           </div>
       </div>
    {% if not created %}
        <form id="team_form" method="post" action="{% url 'teambuilder:create_team' %}">
            {% csrf_token %}
            {% if errors or error%}
                <div class="alert alert-danger">
                    {{errors}}
                    {{error}}
                </div>
            {% endif %}

        <label>Please enter your team name:</label><br/>
          <div class="form-group">
            <input class="form-control" id="id_name" maxlength="100" name="name" type="text" value="{{team.name}}" placeholder="Enter team name" />
        </div><br/>

        <label>Please select the course :</label><br/>
            <div class="form-group">
                <select class="form-control" id="id_course" name="course">
                 {% for course in courses %}
                    <option value="{{course.id}}">{{course.name}}</option>
                {% endfor %}
                </select>
            </div><br/>

        <label>Enter your required skills:</label><br/>
            <div class="form-group">
                <textarea cols="40" id="id_required_skills" maxlength="500" name="required_skills" class="form-control" >{{team.required_skills}}</textarea>
            </div><br/>

        <label>Enter your description:</label><br/>
            <div class="form-group">
                <textarea cols="40" id="id_description" maxlength="500" name="description" class="form-control">{{team.name}}</textarea>
            </div><br/>

        <label>Enter the course password:</label><br/>
            <div class="form-group">
             <input class="form-control" id="id_course_password" maxlength="15" name="course_password" type="text" required placeholder="Enter your course password"/>
        </div><br/>

        <button class="btn btn-success btn-block center-block" type="submit" value="submit">Create</button>

        </form>
    {% endif %}
{% endblock %}

awesome_itech_project/templates/teambuilder/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% block title_block %}Edit profile{% endblock %}
{% block body_block %}
    <h2>Edit profile</h2>
       <div class="row">
           <div class="col-lg-12">
               <ul class="breadcrumb">
                    <li><a href="{% url 'teambuilder:index' %}">Home</a></li>
                   <li><a href="{% url 'teambuilder:profile' profile.user.username   %}">Profile</a></li>
                    <li class="active">Edit profile</li>
               </ul>
           </div>
       </div>

    {% if not created %}
     <div class="row">
            <!-- left column -->
        <div class="col-md-4 col-sm-6 col-xs-12">
          <div class="text-center">
            <img src="/media/{{profile.picture}}/" class="avatar img-circle img-thumbnail" alt="profile photo">
          </div>
        </div>
            <!-- edit form column -->
         <div class="col-lg-8 col-sm-6 col-xs-12 personal-info">
            <form id="profile_form" class="form-horizontal" method="post" action="{% url 'teambuilder:edit_profile' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {% if errors %}
                    <div class="alert alert-danger">
                        {{errors}}
                    </div>
                {% endif %}

                <div class="form-group">
                  <label class="col-lg-3 control-label">First name:</label>
                  <div class="col-lg-8">
                    <input class="form-control" type="text" value="{{user.first_name}}" name="first_name"/>
                  </div>
                </div>

                <div class="form-group">
                  <label class="col-lg-3 control-label">Last name:</label>
                  <div class="col-lg-8">
                    <input class="form-control" type="text" value="{{user.last_name}}" name="last_name"/>
                  </div>
                </div>

                {% if not profile.role  %}
                    <div class="form-group">
                      <label class="col-lg-3 control-label">Role:</label>
                      <div class="col-lg-8">
                          <label class="radio-inline"><input type="radio" value="student" name="role" checked>Student</label>
                          <label class="radio-inline"><input type="radio" value="coordinator" name="role">Coordinator</label>
                      </div>
                    </div>

                {% else %}
                    <div class="form-group hidden">
                      <label class="col-lg-3 control-label">Role:</label>
                      <div class="col-lg-8">
                    {% if profile.role == 'student' %}
                        <label class="radio-inline"><input type="radio" value="student" name="role" checked>Student</label>
                          <label class="radio-inline"><input type="radio" value="coordinator" name="role">Coordinator</label>
                    {% elif profile.role == 'coordinator' %}
                        <label class="radio-inline"><input type="radio" value="student" name="role" >Student</label>
                          <label class="radio-inline"><input type="radio" value="coordinator" name="role" checked>Coordinator</label>
                    {% endif %}
                      </div>
                    </div>
                {% endif %}

                <div class="form-group">
                  <label class="col-lg-3 control-label">Phone number:</label>
                  <div class="col-lg-8">
                    <input class="form-control" id="id_phone_number" maxlength="15" name="phone_number" type="text" value="{{profile.phone_number}}" placeholder="Enter phone number" />
                  </div>
                </div>

                <div class="form-group">
                  <label class="col-lg-3 control-label">About me</label>
                  <div class="col-lg-8">
                    <textarea cols="40" id="id_about_me" maxlength="500" name="about_me" class="form-control">{{profile.about_me}}</textarea>
                  </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-3 control-label">Change display picture:</label>
                    <div class="col-lg-8">
                        <input class="form-control" type="file" name="picture">
                    </div>
                </div>

                <div class="form-group">
                  <label class="col-md-3 control-label"></label>
                  <div class="col-md-4">
                    <button class="btn btn-primary btn-block center-block" type="submit" value="submit">Save changes <span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span></button>
                  </div>
                  <div class="col-md-4">
                    <a href="{% url 'teambuilder:profile' user.username %}" class="btn btn-primary btn-block center-block" type="submit" value="submit">Cancel <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                  </div>
                </div>

            </form>
        {% else %}
            <div class="alert alert-success">
                <p>Your changes have been saved. Click <a href="/teambuilder/profile/{{ user.username }}">here</a> to view profile </p>
            </div>
        {% endif %}
        </div>
     </div>
{% endblock %}

awesome_itech_project/templates/teambuilder/find_team.html
  <div id="latest_teams" class="col-sm-6">
{% if team_list %}
      <div class="table-responsive">
         <table class="table">
                <thead>
                    <td>Team</td><td>Course</td>
                </thead>
                {% for team in team_list %}
                    <tr>
                        <td><a href="{% url 'teambuilder:team_detail' team.slug %}">{{ team.name }}</a></td>
                        <td><a href="{% url 'teambuilder:course_detail' team.course.slug %}">{{ team.course.name }}</a></td>
                    </tr>
                {% endfor %}
         </table>
      </div>
 {% else %}
         <p>No such team exits. Please recheck your typing</p>
 {% endif %}
      </div>

awesome_itech_project/templates/teambuilder/index.html
{% extends 'base.html' %}
{% load static %}
{% block title_block %}Home page{% endblock %}
{% block body_block %}

	<div class="jumbotron">
        <img src="{% static 'images/slider1.jpg' %}" alt="students-image" class="img-responsive">
    </div>

    <div class="row">
         <div class="col-md-6">
            <p class="text-center"><a class="btn btn-lg btn-primary" href="{% url 'teambuilder:search_team' %}" role="button">Find a team</a></p>
        </div>

        <div class="col-md-6">
            <p class="text-center"><a class="btn btn-lg btn-primary" href="{% url 'teambuilder:create_team' %}" role="button">Create a team</a></p>
        </div>
    </div>

    <div class="vertical-space"></div>

    <div class="row well">
        <div id="latest_teams" class="col-sm-6">
            <h3>Recently built teams</h3>
            {% if teams %}
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Team</th>
                                <th>Course</th>
                            </tr>
                        </thead>
                        {% for team in teams %}
                            <tr>
                                <td><a href="{% url 'teambuilder:team_detail' team.slug %}">{{ team.name }}</a></td>
                                <td><a href="{% url 'teambuilder:course_detail' team.course.slug %}">{{ team.course.name }}</a></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% else %}
                <p>No teams have been built</p>
            {% endif %}

        </div>
        <div id="latest_projects" class="col-sm-6">

            <h3>Recently added courses</h3>
            {% if courses %}
                <div class="list-group">
                    {% for course in courses %}
                        <a class="list-group-item" href="{% url 'teambuilder:course_detail' course.slug %}">{{course.name}}</a>
                    {% endfor %}
                </div>
            {% else %}
                <p>No courses have been added</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

awesome_itech_project/templates/teambuilder/logout.html
{% extends 'base.html' %}
{% block title_block %}Logged out {% endblock %}
{% block body_block %}



    <p>This is the logout page</p>



{% endblock %}

awesome_itech_project/templates/teambuilder/search_team.html
{% extends 'base.html' %}
{% block title_block %}Find team{% endblock %}
{% block body_block %}
       <h2>Find team</h2>
       <div class="row">
           <div class="col-lg-12">
               <ul class="breadcrumb">
                    <li><a href="{% url 'teambuilder:index' %}">Home</a></li>
                    <li class="active">Find team</li>
               </ul>
           </div>
       </div>


     <form>
         <label></label>
         <input  class="search-query span10" type="text" name="suggestion" value="" id="suggestion"  />
     </form>
     <ul></ul>
     <div id="teams" class="row" >
          <div class="col-lg-7">
              <div class="table-responsive">
                 <table class="table">
                        <thead>
                            <td>Team</td><td>Course</td>
                        </thead>
                        {% for team in team_list %}
                            <tr>
                                <td><a href="{% url 'teambuilder:team_detail' team.slug %}">{{ team.name }}</a></td>
                                <td><a href="{% url 'teambuilder:course_detail' team.course.slug %}">{{ team.course.name }}</a></td>
                            </tr>
                        {% endfor %}
                 </table>
              </div>
          </div>
     </div>

{% endblock %}