awesome_itech_project/awesome_itech_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from registration.backends.simple.views import RegistrationView
from registration.forms import RegistrationFormUniqueEmail
from django.conf import settings

class MyRegistrationView(RegistrationView):
    form_class=RegistrationFormUniqueEmail
    def get_success_url(self, user):
        return '/teambuilder/edit-profile/'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'awesome_itech_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^teambuilder/', include('teambuilder.urls', namespace='teambuilder')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
)

# let's just use django for now to serve static media as our application does not anticipate any load at the moment
urlpatterns += patterns(
    'django.views.static',
    (r'^media/(?P<path>.*)',
    'serve',
    {'document_root': settings.MEDIA_ROOT}), )

awesome_itech_project/teambuilder/urls.py
from django.conf.urls import patterns, include, url
from teambuilder import views

app_name = 'teambuilder'
urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^create-team/$', views.create_team, name='create_team'),
    url(r'^add-course/$', views.add_course, name='add_course'),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
    url(r'^edit-profile/$', views.edit_profile, name='edit_profile'),
    url(r'^team/(?P<team_name_slug>[\w\-]+)/$', views.team_details, name='team_detail'),
    url(r'^team/(?P<team_name_slug>[\w\-]+)/edit/$', views.edit_team, name='edit_team'),
    url(r'^course/(?P<course_name_slug>[\w\-]+)/$', views.course_details, name='course_detail'),
    url(r'^course/(?P<course_name_slug>[\w\-]+)/edit/$', views.edit_course, name='edit_course'),
    url(r'^course/(?P<course_name_slug>[\w\-]+)/teams/$', views.view_course_teams, name='view_course_teams'),
    url(r'^find-team/$', views.find_team, name='find_team'),
    url(r'^search-team/$', views.search_team, name='search_team'),
    url(r'^team/(?P<team_name_slug>[\w\-]+)/send-request/$', views.join_team, name='join_team'),
    url(r'^team/(?P<team_name_slug>[\w\-]+)/cancel-request/$', views.cancel_request, name='cancel_request'),
    url(r'^team/(?P<team_name_slug>[\w\-]+)/view-requests/$', views.view_requests, name='view_requests'),
    url(r'^team/(?P<team_name_slug>[\w\-]+)/view-members/$', views.view_team_members, name='view_team_members'),
    url(r'^request/(?P<request_id>[\w\-]+)/accept/$', views.accept_request, name='accept_request'),
    url(r'^request/(?P<request_id>[\w\-]+)/reject/$', views.reject_request, name='reject_request'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^unauthorized/$', views.unauthorized, name='unauthorized'),
    url(r'^page-not-found/$', views.page_not_found, name='page_not_found'),
    url(r'^course/(?P<course_name_slug>[\w\-]+)/merge-teams/$', views.merge_teams, name='merge_teams'),

)

awesome_itech_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>TeamUp - {%block title_block%}Build a team{% endblock%}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static  'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--add the following link, it the css page of the original page-->
    <!--<link href="{% static  'css/dashboard.css' %}" rel="stylesheet">-->
    <link href="{% static  'css/modern-business.css' %}" rel="stylesheet">

    <!--<link href="{% static 'css/signin.css' %}" rel="stylesheet" />-->
    <link href="{% static 'css/searchtable.css' %}" rel="stylesheet" />

    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->

    <!--datatable css -->
    <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}"/>

    <link rel="stylesheet" href="{% static 'css/teambuilder.css' %}"/>

    <script type="text/javascript" src="{% static 'css/jquery-ui.css' %}"></script>

  </head>

  <body>

        <nav class="navbar navbar-inverse navbar-fixed-top" >
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'teambuilder:index' %}"><img src="{% static 'images/logo.png' %}" alt="TeamUp" width="150" height="50" /></a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'teambuilder:index' %}"><span class="glyphicon glyphicon-home"></span> Home</a> </li>
                <li><a href="{% url 'teambuilder:about' %}">About</a> </li>
                {% if not user.is_authenticated %}
                    <li><a href="{% url 'auth_login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a> </li>
                    <li><a href="{% url 'registration_register' %}"><span class="glyphicon glyphicon-user"></span> Register</a> </li>
                {% else %}
                <li><a href="{% url 'teambuilder:search_team' %}"><span class="glyphicon glyphicon-search"></span> Find team</a> </li>
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user"></span> {{user.username}}<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'teambuilder:dashboard' %}">Dashboard</a> </li>
                    <li><a href="/teambuilder/profile/{{ user.username }}">View profile</a></li>
                    <li><a href="{% url 'auth_password_change' %}">Change Password</a> </li>

                    <li><a href="{% url 'auth_logout' %}"> Logout</a> </li>
                  </ul>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>

        <div class="container" id="body_div">
        {% block body_block %}{% endblock %}
        </div>


          <div class="container-fluid navbar-inverse" id="footer_div">
                <p class="text-center">&copy; Team Awesome 2016</p>
          </div>
     <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
      <!--[if lt IE 9]>
        <script src="{% static 'js/html5shiv.min.js' %}"></script>
        <script src="{% static 'js/respond.min.js' %}"></script>
      <![endif]-->

      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/teambuilder_jquery.js' %}"></script>
      <!-- datatable javascript -->
      <script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %}"></script>

      <!--jqueryUI -->
      <script type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>
  </body>

</html>